[download]
download_path = "./download"

[login]
username = "s112233"
password = "your-password-here"

[[courses]]
name = "Underwater Basket Weaving"
ignore = ["Very Large Files"]
download_virtual_classroom = true

[[courses]]
name = "Chemistry"
